platform:ios, '7.0'
pod 'Masonry', '~> 1.0.1'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'MBProgressHUD', '~> 1.0.0'